### PR TITLE
[4105][wordify][angular] Blueprint Detailing

### PR DESCRIPTION
**Pull request by jvega190**
craftercms/craftercms#4105

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
I don't think shouldn't be any form-definition, config or other XML files here. Pull from next and update PR so we can review a bit cleaner.

**Review by rart — CHANGES_REQUESTED** [review]
Please updated based on latest changes: remove of post page or anything else that renders this outdated

**Comment by rart** [comment]
What’s up with these updates? Never came through @jvega190

**Comment by jvega190** [comment]
Closing this because it's showing as `from unknown repository`, will create PR again

**Pull request closed without merging**
